env:
  node: true
  es6: true

extends:
  - airbnb-base

parserOptions:
  ecmaVersion: 13
  sourceType: module

plugins:
  - import

rules:
  semi:
    - 2
    - never
  import/extensions:
    - error
    - always
