image: golang:1.17-alpine

variables:
  REPO_NAME: gitlab.com/easbarba/pak

before_script:
  - apk add build-base
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages:
  - test
  - build

format:
  stage: test
  script:
    - go fmt $(go list ./...)
    - go vet $(go list ./...)
    - go test -race $(go list ./...)

compile:
  stage: build
  script:
    - go build -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/pak cmd/pak/main.go
  artifacts:
    paths:
      - pak
