name: Java Pipeline with Gradle

on:
  push:
    branches: [ java ]
  pull_request:
    branches: [ java ]

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Execute Gradle test
      run: ./gradlew test
